config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'fbsessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'fbsessions#destroy', as: 'signout'
  resources :fbsessions, only: [:create, :destroy]
  resource :fbhome, only: [:show]
  get 'fbsessions/create'
  get 'fbsessions/destroy'
  get 'fbhome/show'

  resources :videos
  resources :emailusers
  resources :articles, only: [:index, :new, :create, :destroy]
    
  get 'articles/index'

  get 'articles/new'

  get 'articles/create'

  get 'articles/destroy'

  resources :statuses
  resources :post1s do
    member do # 客製化連結
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  
  get "contact", to: "pages#contact"
  get "error", to: "pages#error"
  
  get "ref1", to: redirect("http://railscasts.com")
  get "ref2", to: redirect("https://gorails.com")
  get "ref3", to: redirect("https://railstutorial.org")
  get "ref1001", to: redirect("https://www.youtube.com/watch?v=N-4NuoivKu0")
  get "ref1002", to: redirect("https://www.youtube.com/watch?v=cvYVpMK_Vv4&list=PLskZP4iE0Xzb7tp95ruIxJnXW12lOzeLh&index=1")
  get "ref1003", to: redirect("https://www.youtube.com/watch?v=exEduZlJS7Q&list=PLDmvslp_VR0xlwr5lAx2PDsZLu7oIOhpX")
  get "ref1004", to: redirect("https://www.tutorialspoint.com/ruby-on-rails/rails-file-uploading.htm")
  get "ref1005", to: redirect("http://guides.rubyonrails.org/action_mailer_basics.html")
  get "ref1006", to: redirect("http://api.rubyonrails.org/")
  get "ref1007", to: redirect("https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/base.rb")
  get "ref1008", to: redirect("https://sendgrid.com/docs/Integrate/Frameworks/rubyonrails.html")
  get "ref1009", to: redirect("https://www.udemy.com/draft/537712/learn/v4/t/lecture/3153934?start=105")
  get "ref1010", to: redirect("https://wistia.com/doc/embed-links")
  get "ref1011", to: redirect("https://www.producthunt.com/posts/code4startup")
  get "ref1012", to: redirect("https://github.com/leotrieu/Code4Startup.Ninja")
  get "ref1013", to: redirect("https://code4startup.com/subscriptions")
  get "ref1014", to: redirect("https://code4startup.com/projects/uber-app-for-food-with-python-django-and-swift?code=SPECIAL")
  get "ref1015", to: redirect("https://richonrails.com/articles/facebook-authentication-in-ruby-on-rails")
  get "ref1016", to: redirect("https://github.com/mkdynamic/omniauth-facebook")

  get "ref4",to: redirect("http://railsforzombies.org")
  get "ref5", to: redirect("https://thoughtbot.com/upcase/rails")
  get "ref6", to: redirect("http://guides.rubyonrails.org/")
  get "ref7", to: redirect("http://learn-rails.com/")
  get "ref8", to: redirect("http://www.theodinproject.com/")
  get "ref9", to: redirect("https://github.com/eliotsykes/rspec-rails-examples")
  get "ref10", to: redirect("http://awesome-ruby.com/")
  get "ref11", to: redirect("https://github.com/ekremkaraca/awesome-rails")
  get "ref12", to: redirect("https://rvm.io/")
  get "ref13", to: redirect("https://github.com/rbenv/rbenv#readme")
  get "ref14", to: redirect("https://www.udemy.com/courses/")
  get "ref15", to: redirect("https://www.skillshare.com/home")
  get "ref16", to: redirect("https://www.codecademy.com/learn/all")
  get "ref17", to: redirect("https://www.freecodecamp.com/")
  get "ref1000", to: redirect("https://www.lynda.com/")  
  get "ref101", to: redirect("https://www.python.org/")            
  get "ref102", to: redirect("https://simpleprogrammer.com/2017/02/15/get-started-learning-python/")            
  get "ref103", to: redirect("https://realpython.com/")            
  get "ref104", to: redirect("https://training.talkpython.fm/courses/explore_python_jumpstart/python-language-jumpstart-building-10-apps")            
  get "ref105", to: redirect("https://learnpythonthehardway.org/book/")            
  get "ref106", to: redirect("https://www.codecademy.com/learn/python")            
  get "ref107", to: redirect("https://www.codeschool.com/learn/python")            
  get "ref108", to: redirect("https://training.talkpython.fm/courses/explore_entrepreneurs/python-for-entrepreneurs-build-and-launch-your-online-business")            
  get "ref109", to: redirect("https://www.datacamp.com/courses/intro-to-python-for-data-science")            
  get "ref110", to: redirect("https://www.amazon.com/gp/product/1449355730/ref=as_li_ss_tl?ie=UTF8&linkCode=sl1&tag=trndingcom-20&linkId=963e5708fd96380e4d706d280dd8f477")            
  get "ref111", to: redirect("https://www.amazon.com/exec/obidos/ASIN/1593275994/makithecompsi-20")            
  get "ref112", to: redirect("https://www.udemy.com/learning-python-not-the-snake/learn/v4/overview")  
  get "ref113", to: redirect("https://www.pyimagesearch.com/practical-python-opencv/") 
  get "ref114", to: redirect("https://www.pythonanywhere.com/") 
  get "ref115", to: redirect("https://simpleprogrammer.com/2017/01/18/7-reasons-why-you-should-learn-python/") 

  get "about", to: "pages#about"

  resources :comments
  resources :connections
  resources :categories
  resources :posts
  resources :users, only: [:new, :create]
  resources :statuses
  resources :searches
  
  root 'pages#home'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  

end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:online, :vote_count, :user_id)
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<%= form_for(@status) do |f| %>
  <% if @status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% @status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :online %><br>
    <%= f.check_box :online %>
  </div>
  <div class="field">
    <%= f.label :vote_count %><br>
    <%= f.number_field :vote_count %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form' %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Online</th>
      <th>Vote count</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.online %></td>
        <td><%= status.vote_count %></td>
        <td><%= status.user_id %></td>
        <td><%= link_to 'Show', status %></td>
        <td><%= link_to 'Edit', edit_status_path(status) %></td>
        <td><%= link_to 'Destroy', status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Status', new_status_path %>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form' %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Online:</strong>
  <%= @status.online %>
</p>

<p>
  <strong>Vote count:</strong>
  <%= @status.vote_count %>
</p>

<p>
  <strong>User:</strong>
  <%= @status.user_id %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>