config/routes.rb
Rails.application.routes.draw do
  
  get 'auth/:provider/callback', to: 'fbsessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'fbsessions#destroy', as: 'signout'
  resources :fbsessions, only: [:create, :destroy]
  resource :fbhome, only: [:show]
  get 'fbsessions/create'
  get 'fbsessions/destroy'
  get 'fbhome/show'

  resources :videos
  resources :emailusers
  resources :articles, only: [:index, :new, :create, :destroy]
    
  get 'articles/index'

  get 'articles/new'

  get 'articles/create'

  get 'articles/destroy'

  resources :statuses
  resources :post1s do
    member do # 客製化連結
      post :vote
    end
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  
  get "contact", to: "pages#contact"
  get "error", to: "pages#error"
  
  get "ref1", to: redirect("http://railscasts.com")
  get "ref2", to: redirect("https://gorails.com")
  get "ref3", to: redirect("https://railstutorial.org")
  get "ref1001", to: redirect("https://www.youtube.com/watch?v=N-4NuoivKu0")
  get "ref1002", to: redirect("https://www.youtube.com/watch?v=cvYVpMK_Vv4&list=PLskZP4iE0Xzb7tp95ruIxJnXW12lOzeLh&index=1")
  get "ref1003", to: redirect("https://www.youtube.com/watch?v=exEduZlJS7Q&list=PLDmvslp_VR0xlwr5lAx2PDsZLu7oIOhpX")
  get "ref1004", to: redirect("https://www.tutorialspoint.com/ruby-on-rails/rails-file-uploading.htm")
  get "ref1005", to: redirect("http://guides.rubyonrails.org/action_mailer_basics.html")
  get "ref1006", to: redirect("http://api.rubyonrails.org/")
  get "ref1007", to: redirect("https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/base.rb")
  get "ref1008", to: redirect("https://sendgrid.com/docs/Integrate/Frameworks/rubyonrails.html")
  get "ref1009", to: redirect("https://www.udemy.com/draft/537712/learn/v4/t/lecture/3153934?start=105")
  get "ref1010", to: redirect("https://wistia.com/doc/embed-links")
  get "ref1011", to: redirect("https://www.producthunt.com/posts/code4startup")
  get "ref1012", to: redirect("https://github.com/leotrieu/Code4Startup.Ninja")
  get "ref1013", to: redirect("https://code4startup.com/subscriptions")
  get "ref1014", to: redirect("https://code4startup.com/projects/uber-app-for-food-with-python-django-and-swift?code=SPECIAL")
  get "ref1015", to: redirect("https://richonrails.com/articles/facebook-authentication-in-ruby-on-rails")
  get "ref1016", to: redirect("https://github.com/mkdynamic/omniauth-facebook")

  get "ref4",to: redirect("http://railsforzombies.org")
  get "ref5", to: redirect("https://thoughtbot.com/upcase/rails")
  get "ref6", to: redirect("http://guides.rubyonrails.org/")
  get "ref7", to: redirect("http://learn-rails.com/")
  get "ref8", to: redirect("http://www.theodinproject.com/")
  get "ref9", to: redirect("https://github.com/eliotsykes/rspec-rails-examples")
  get "ref10", to: redirect("http://awesome-ruby.com/")
  get "ref11", to: redirect("https://github.com/ekremkaraca/awesome-rails")
  get "ref12", to: redirect("https://rvm.io/")
  get "ref13", to: redirect("https://github.com/rbenv/rbenv#readme")
  get "ref14", to: redirect("https://www.udemy.com/courses/")
  get "ref15", to: redirect("https://www.skillshare.com/home")
  get "ref16", to: redirect("https://www.codecademy.com/learn/all")
  get "ref17", to: redirect("https://www.freecodecamp.com/")
  get "ref1000", to: redirect("https://www.lynda.com/")  
  get "ref101", to: redirect("https://www.python.org/")            
  get "ref102", to: redirect("https://simpleprogrammer.com/2017/02/15/get-started-learning-python/")            
  get "ref103", to: redirect("https://realpython.com/")            
  get "ref104", to: redirect("https://training.talkpython.fm/courses/explore_python_jumpstart/python-language-jumpstart-building-10-apps")            
  get "ref105", to: redirect("https://learnpythonthehardway.org/book/")            
  get "ref106", to: redirect("https://www.codecademy.com/learn/python")            
  get "ref107", to: redirect("https://www.codeschool.com/learn/python")            
  get "ref108", to: redirect("https://training.talkpython.fm/courses/explore_entrepreneurs/python-for-entrepreneurs-build-and-launch-your-online-business")            
  get "ref109", to: redirect("https://www.datacamp.com/courses/intro-to-python-for-data-science")            
  get "ref110", to: redirect("https://www.amazon.com/gp/product/1449355730/ref=as_li_ss_tl?ie=UTF8&linkCode=sl1&tag=trndingcom-20&linkId=963e5708fd96380e4d706d280dd8f477")            
  get "ref111", to: redirect("https://www.amazon.com/exec/obidos/ASIN/1593275994/makithecompsi-20")            
  get "ref112", to: redirect("https://www.udemy.com/learning-python-not-the-snake/learn/v4/overview")  
  get "ref113", to: redirect("https://www.pyimagesearch.com/practical-python-opencv/") 
  get "ref114", to: redirect("https://www.pythonanywhere.com/") 
  get "ref115", to: redirect("https://simpleprogrammer.com/2017/01/18/7-reasons-why-you-should-learn-python/") 

  get "about", to: "pages#about"

  resources :comments
  resources :connections
  resources :categories
  resources :posts
  resources :users, only: [:new, :create]
  resources :statuses
  resources :searches
  
  root 'pages#home'
  get '/register', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  

end

app/models/article.rb
class Article < ActiveRecord::Base
 mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
 validates :name, presence: true # Make sure the owner's name is present.    
end

app/models/category.rb
class Category < ActiveRecord::Base
   has_many :connections
   has_many :posts, through: :connections
   has_many :post1s
end

app/models/comment.rb
class Comment < ActiveRecord::Base
   belongs_to :post
   belongs_to :post1
   belongs_to :user

  has_many :votes, as: :voteable

  def up_votes
    self.votes.where(vote: true).length
  end

  def down_votes
    self.votes.where(vote: false).length
  end

  def total_votes
    up_votes - down_votes
  end   
end

app/models/connection.rb
class Connection < ActiveRecord::Base
   belongs_to :post
   belongs_to :category
end

app/models/emailuser.rb
class Emailuser < ActiveRecord::Base
end

app/models/fbuser.rb
# This code will take the data returned by Facebook, try to find a corresponding user
# in our database, and then update or create the user as necessary. 
class Fbuser < ActiveRecord::Base 
  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_initialize.tap do |fbuser|
      fbuser.provider = auth.provider
      fbuser.uid = auth.uid
      fbuser.name = auth.info.name
      fbuser.oauth_token = auth.credentials.token
      fbuser.oauth_expires_at = Time.at(auth.credentials.expires_at)
      fbuser.save!
    end
  end    
end

app/models/post.rb
class Post < ActiveRecord::Base
   has_many :connections
   has_many :categories, through: :connections 
   has_many :comments
end

app/models/post1.rb
class Post1 < ActiveRecord::Base
   belongs_to :category
   belongs_to :user
   has_many :comments 
   has_many :votes, as: :voteable

  def up_votes
    self.votes.where(vote: true).length
  end

  def down_votes
    self.votes.where(vote: false).length
  end

  def total_votes
    up_votes - down_votes
  end   
  
  def self.search(keyword)
    post1s = order(:title)
    post1s = post1s.where("title like ?", "%#{keyword}%") if keyword.present?
    post1s
  end
end

app/models/serach.rb
class Serach < ActiveRecord::Base
  def post1s
    @post1s ||= find_post1s
  end
  
private
  def find_post1s
    post1s = Post1.order(:title)
    post1s = post1s.where("title like ?", "%#{keyword}%") if keyword.present?
    post1s
  end
end
   

app/models/status.rb
class Status < ActiveRecord::Base
   belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
   has_secure_password validation: false
   has_many :post1s   
   has_many :comments  
   has_one :status
end

app/models/video.rb
class Video < ActiveRecord::Base
  def next
    # Video.find(id+1)
    Video.where("id > ?",id).first
  end
  def prev
    # Video.find(id-1)
    Video.where("id < ?",id).last
  end    
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  # 關聯的設定可以給別名，foreign key 和相關連的 model 需要自己設定  
  belongs_to :creator, foreign_key: :user_id, class_name: "User"
  belongs_to :voteable, polymorphic: true
  #belongs_to :post1
  validates_uniqueness_of :creator, scope: [:voteable_type, :voteable_id]
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/fbhome_helper.rb
module FbhomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/post1s_helper.rb
module Post1sHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/shared/_nav.html.erb
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul>
        <% if logged_in? %>
          <ul class="nav navbar-nav navbar-right">
            <large>Welcome! <%= current_user.name %></large>
          </ul>
          <li><%= link_to 'Logout', logout_path %></li>
        <% else %>
          <ul class="nav navbar-nav navbar-right">
            <large>Please Login to add contents</large>
          </ul>
          <li><%= link_to 'Login', login_path %></li>  
          <li><%= link_to 'Register', register_path %></li>
        <% end %>
      </ul>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!--<a class="navbar-brand" id="logo" href="#">PostIt</a>-->
      <%= link_to "uCast",root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <!--<li><a href="#">Link <span class="sr-only">(current)</span></a></li>-->
        <li><%= link_to  "About", about_path %></li>
        <!--<li><a href="#">Link</a></li>-->
        <!--li><!--%= link_to  "Contact", contact_path %></li-->        
<% if logged_in? %>   
<!--% if current_user.name != "admin"% -->
        <li><%= link_to  "Category", categories_path %></li>
        <li><%= link_to  "Post", post1s_path %></li>        
<!--% end % -->
<% end %>
      </ul>
     <% if logged_in? %>   
     <!--% if (current_user.name == "admin") %-->
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <!--<li><a href="#">Link</a></li>-->
        <!--li><!--%= link_to  "railscasts.com", ref1_path %></li-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Developer<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to  "http://railscasts.com", ref1_path %></li>
            <li><%= link_to  "https://gorails.com", ref2_path %></li>
            <li><%= link_to  "https://railstutorial.org", ref3_path %></li>
            <li><%= link_to  "Ruby on Rails Tutorial full sample lesson(Rails 5)-YouTube",ref1001_path %></li>
            <li><%= link_to  "Ruby on Rails 5: Essential Training-YouTube(100 videos)",ref1002_path %></li>
            <li><%= link_to  "Learn Ruby on Rails from Scratch-Youtube(38v ideos)", ref1003_path %></li>
            <li><%= link_to  "https://www.tutorialspoint.com/ruby-on-rails", ref1004_path %></li>
            <li><%= link_to  "http://guides.rubyonrails.org/action_mailer_basics.html", ref1005_path %></li>
            <li><%= link_to  "http://api.rubyonrails.org/", ref1006_path %></li>
            <li><%= link_to  "https://github.com/rails/rails/blob/master/actionmailer/lib/action_mailer/base.rb",ref1007_path %></li>
            <li><%= link_to  "https://sendgrid.com/docs/Integrate/Frameworks/rubyonrails.html",ref1008_path %></li>
            <li><%= link_to  "https://www.udemy.com/draft/537712/learn/v4/t/lecture/3153934?start=105", ref1009_path %></li>
            <li><%= link_to  "https://wistia.com/doc/embed-links", ref1010_path %></li>
            <li><%= link_to  "https://www.producthunt.com/posts/code4startup", ref1011_path %></li>
            <li><%= link_to  "https://github.com/leotrieu/Code4Startup.Ninja", ref1012_path %></li>
            <li><%= link_to  "https://code4startup.com/subscriptions", ref1013_path %></li>
            <li><%= link_to  "https://code4startup.com/projects/uber-app-for-food-with-python-django-and-swift?code=SPECIAL", ref1014_path %></li>
            <li><%= link_to  "https://richonrails.com/articles/facebook-authentication-in-ruby-on-rails", ref1015_path %></li>
            <li><%= link_to  "https://github.com/mkdynamic/omniauth-facebook", ref1016_path %></li>
            
            <li><%= link_to  "http://railsforzombies.org", ref4_path %></li>
            <li><%= link_to  "https://thoughtbot.com/upcase/rails", ref5_path %></li>
            <li><%= link_to  "http://guides.rubyonrails.org/", ref6_path %></li>
            <li><%= link_to  "http://learn-rails.com/", ref7_path %></li>
            <li><%= link_to  "http://http://www.theodinproject.com/", ref8_path %></li>
            <!--%= link_to  "https://drive.google.com/file/d/0B6S6WKwpSu8IRndCQWM0OGZWWDQ/view", ref8_path %></li-->
            <li><%= link_to  "https://github.com/eliotsykes/rspec-rails-examples", ref9_path %></li>
            <li><%= link_to  "http://awesome-ruby.com/", ref10_path %></li>
            <li><%= link_to  "https://github.com/ekremkaraca/awesome-rails", ref11_path %></li>
            <li><%= link_to  "https://rvm.io/", ref12_path %></li>
            <li><%= link_to  "https://github.com/rbenv/rbenv#readme", ref13_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to  "https://www.udemy.com/courses/", ref14_path %></li>
            <li><%= link_to  "https://www.skillshare.com/home", ref15_path %></li>
            <li><%= link_to  "https://www.codecademy.com/learn/all", ref16_path %></li>
            <li><%= link_to  "https://www.freecodecamp.com/", ref17_path %></li>
            <li><%= link_to  "https://www.lynda.com/", ref1000_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to  "https://www.python.org/", ref101_path %></li>
            <li><%= link_to  "https://simpleprogrammer.com/2017/02/15/get-started-learning-python/", ref102_path %></li>
            <li><%= link_to  "https://realpython.com/", ref103_path %></li>
            <li><%= link_to  "https://training.talkpython.fm/courses/explore_python_jumpstart/", ref104_path %></li>
            <li><%= link_to  "https://learnpythonthehardway.org/book/", ref105_path %></li>
            <li><%= link_to  "https://www.codecademy.com/learn/python", ref106_path %></li>
            <li><%= link_to  "https://www.codeschool.com/learn/python", ref107_path %></li>
            <li><%= link_to  "https://training.talkpython.fm/courses/explore_entrepreneurs/", ref108_path %></li>
            <li><%= link_to  "https://www.datacamp.com/courses/intro-to-python-for-data-science", ref109_path %></li>
            <li><%= link_to  "https://www.amazon.com/gp/product/1449355730", ref110_path %></li>
            <li><%= link_to  "https://www.amazon.com/exec/obidos/ASIN/1593275994/makithecompsi-20", ref111_path %></li>          
            <li><%= link_to  "https://www.udemy.com/learning-python-not-the-snake/learn/v4/overview", ref112_path %></li>  
            <li><%= link_to  "https://www.pyimagesearch.com/practical-python-opencv/", ref113_path %></li>  
            <li><%= link_to  "https://www.pythonanywhere.com/", ref114_path %></li>  
            <li><%= link_to  "https://simpleprogrammer.com/2017/01/18/7-reasons-why-you-should-learn-python/", ref115_path %></li>  
            <!--<li><!--%= link_to  "", ref116_path %></li>  -->
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Admin <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to  "User Status", contact_path %></li>   
            <li><%= link_to  "File Upload", articles_path %></li>   
            <li><%= link_to  "Hosted Video Upload", videos_path %></li>   
            <li><%= link_to  "Send Email", emailusers_path %></li>   
<%
=begin%>
            <li><%= link_to  "Category", categories_path %></li>
            <li><%= link_to  "Post", posts_path %></li>
            <li><%= link_to  "Connection", connections_path %></li>
            <li><%= link_to  "Comment", comments_path %></li>         
            <li><%= link_to  "Post1", post1s_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
<%
=end%>
          </ul>
        </li>
      </ul>
      <!--% end %-->
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/shared/_title.html.erb
<h4><%= title %></h4>
<hr>